name: publish
on: [push]
jobs:
  publish-mattermost-arm64:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ github.repository_owner }}/mattermost
    steps:
    - name: Checkout the code  
      uses: actions/checkout@v3

    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/arm64
        build-args: |
          MM_VERSION=7.3.0
        push: true
        tags: ghcr.io/${DOCKER_IMAGE}:latest,ghcr.io/${DOCKER_IMAGE}:7.3.0